# filepath: /rpi-voice-detect/rpi-voice-detect/src/config/default.yaml
audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  format: "int16"

model:
  path: "models/voice_detection_model.pb"
  confidence_threshold: 0.5

mqtt:
  broker: "mqtt://localhost"
  port: 1883
  topic: "voice/detection"

http_api:
  host: "0.0.0.0"
  port: 5000

logging:
  level: "INFO"
  file: "logs/app.log"